// @deprecated — archived in Phase 1 (2026-07-14). Transition phrases now in `content_templates` table.
// See docs/DATABASE_ARCHITECTURE.md → 005_content_templates.sql

export const TRANSITIONS: string[] = [
  "Next update coming your way…",
  "In regional news today…",
  "Moving to traffic updates…",
  "Here's what's happening now…",
  "Now for the latest reports…",
  "Continuing with today's stories…",
  "And now from our news desk…",
  "Let's look at what else is making headlines…",
  "We now continue with the latest updates.",
  "We continue shortly with more news.",
  "Now moving to the next segment.",
  "Up next, developments from the region.",
  "We now move to the latest reports.",
  "Continuing with today's stories.",
  "Here's what else is happening.",
  "More news coming up in just a moment.",
  "Stay with us for the next story.",
  "Now turning our attention to…",
  "Here's another update for you.",
  "We'll be right back with more.",
  "Now for the next item in our bulletin.",
  "Let's continue with our coverage.",
  "Here's the latest from our news feed.",
  "Moving on to the next story.",
  "And now, more from the news desk.",
  "Here's another development we're tracking.",
  "Now for our next update.",
  "Let's get to the next story.",
  "Here's what's coming up next.",
  "We continue with more news now.",
  "And now, the latest headlines.",
  "Here's another story for you.",
  "Moving forward with our coverage.",
  "Now for the next report.",
  "Let's continue with today's coverage.",
  "Here's what's next in our bulletin.",
  "We now bring you the next story.",
  "And now, more from the newsroom.",
  "Here's another update we have for you.",
  "Now turning to the next item.",
  "Let's continue with our news update.",
  "Here's the next story in our lineup.",
  "We now move to the next segment.",
  "And now, more news for you.",
  "Here's what's coming up in our bulletin.",
  "Now for the next development.",
  "Let's continue with our reporting.",
  "Here's the next story we have for you.",
  "We now bring you another update.",
  "And now, the next item in our news.",
  "Here's what's next on our news desk.",
  "Now for the next story in our coverage.",
  "Let's continue with more updates.",
  "Here's the next report we have.",
  "We now move to the next update.",
  "And now, more from our news team.",
  "Here's another story coming your way.",
  "Now for the next item in our bulletin.",
  "Let's continue with today's news.",
  "Here's what's next in our coverage.",
  "We now bring you the next report.",
  "And now, more news updates.",
  "Here's the next story for you.",
  "Now turning to the next development.",
  "Let's continue with our news bulletin.",
  "Here's what's coming up next.",
  "We now move to the next story.",
  "And now, more from the news feed.",
  "Here's another update we're following.",
  "Now for the next item in our report.",
  "Let's continue with more coverage.",
  "Here's the next development we have.",
  "We now bring you another story.",
  "And now, the next update in our news.",
  "Here's what's next on our desk.",
  "Now for the next story in our update.",
  "Let's continue with our reporting.",
  "Here's the next item we have for you.",
  "We now move to the next bulletin.",
  "And now, more news for our listeners.",
  "Here's another story coming up.",
  "Now for the next development in our coverage.",
  "Let's continue with more stories.",
  "Here's what's next in our news report.",
  "We now bring you the next update.",
  "And now, more from our newsroom.",
  "Here's the next story we're tracking.",
  "Now turning to the next item.",
  "Let's continue with our news updates.",
  "Here's what's coming up in our report.",
  "We now move to the next segment.",
  "And now, more news for you.",
  "Here's another update we have.",
  "Now for the next story in our lineup.",
  "Let's continue with our coverage.",
  "Here's the next development for you.",
  "We now bring you another report.",
  "And now, the next item in our news.",
  "Here's what's next on our news desk.",
  "Now for the next story in our bulletin.",
  "Let's continue with more updates.",
  "Here's the next report we have.",
  "We now move to the next update.",
  "And now, more from our news team.",
  "Here's another story coming your way.",
  "Now for the next item in our report.",
  "Let's continue with our news bulletin.",
  "Here's what's coming up next.",
  "We now move to the next story.",
  "And now, more from the news feed.",
  "Here's another update we're following.",
  "Now for the next item in our coverage.",
  "Let's continue with more coverage.",
  "Here's the next development we have.",
  "We now bring you another story.",
  "And now, the next update in our news.",
  "Here's what's next on our desk.",
  "Now for the next story in our update.",
  "Let's continue with our reporting.",
  "Here's the next item we have for you.",
  "We now move to the next bulletin.",
  "And now, more news for our listeners.",
  "Here's another story coming up.",
  "Now for the next development in our coverage.",
  "Let's continue with more stories.",
  "Here's what's next in our news report.",
  "We now bring you the next update.",
  "And now, more from our newsroom.",
  "Here's the next story we're tracking.",
  "Now turning to the next item.",
  "Let's continue with our news updates.",
  "Here's what's coming up in our report.",
];

export const COMING_UP_TEASERS: string[] = [
  "Coming up, more stories from our news desk.",
  "Still to come, the latest developments.",
  "Up next, more updates for you.",
  "Stay tuned for more news ahead.",
  "More stories coming your way shortly.",
  "We have more updates coming up.",
  "Still ahead, the latest headlines.",
  "Coming up, more from our news team.",
  "Stay with us for more stories.",
  "More news still to come.",
  "Up next, additional reports.",
  "Coming your way, more coverage.",
  "Still to come, breaking developments.",
  "We'll have more stories shortly.",
  "Stay tuned for the latest updates.",
  "More news ahead on our broadcast.",
  "Coming up, more from the region.",
  "Still ahead, today's top stories.",
  "We have more coverage coming.",
  "Stay with us for more headlines.",
];
