// Re-exports types from src/lib/types.ts for legacy modules.
export type {
  NewsCategory,
  NewsItem,
  RadioScript,
  BroadcastQueueItem,
  Alert,
  Feed,
  QueueItem,
  StationRecord,
  ContentSource,
  StationSource,
  BroadcastType,
  BroadcastItem,
  PlaybackState,
  VoiceOption,
  ITTSProvider,
  FeedHealth,
  DiagnosticResult,
  DiagnosticSummary,
  ScriptSegment,
  BroadcastScript,
  IScriptGenerator,
  BroadcastMode,
  StationTimeInfo,
  FrenchBulletinSlot,
  NextSegment,
  BroadcastStateValue,
  PersistedBroadcastState,
  SerializedNewsItem,
  UnifiedEvent,
  ProviderHealth,
} from '../../lib/types';
export { getFlagEmoji } from '../../lib/types';
